# Generated by Django 2.1 on 2019-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ящика')),
                ('coord_x', models.IntegerField(blank=True, null=True, verbose_name='Координата X')),
                ('coord_y', models.IntegerField(blank=True, null=True, verbose_name='Координата Y')),
                ('coord_z', models.IntegerField(blank=True, null=True, verbose_name='Координата Z')),
            ],
            options={
                'verbose_name': 'Волшебный ящик',
                'verbose_name_plural': 'Волшебные ящики',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='maps/', verbose_name='Файл карты')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='номер')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
    ]
