# Generated by Django 2.1 on 2019-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
    ]
