# Generated by Django 2.1 on 2019-01-02 16:32

from django.db import migrations, models
import django.db.models.deletion
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_map_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='chest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploader.Chest'),
        ),
        migrations.AlterField(
            model_name='map',
            name='file',
            field=models.FileField(upload_to='maps/', validators=[uploader.models.file_size], verbose_name='Файл карты'),
        ),
    ]
